name: graphql_ppx_re pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

jobs:
  test_and_build_alpine:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }} with alpine Docker
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]

    steps:
      - uses: docker://node:12.6-alpine
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: |
          npm install -g esy@latest cross-env
      # OCaml 4.06 and BuckleScript 6
      - name: install-build
        run: |
          esy install 
          esy b
      - name: test-native
        run: |
          esy b dune runtest -f
      - name: test-bsb6
        run: |
          cd tests_bucklescript
          node ./run.js bsb6
      # OCaml 4.02 and BuckleScript 5
      - name: install-build @402
        run: |
          esy @402 install
          esy @402 b
      - name: test-bsb5
        run: |
          cd tests_bucklescript
          node ./run.js bsb5
        env:
          CI: true

  test_and_build:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup
        run: |
          npm install -g esy@latest cross-env
      # OCaml 4.06 and BuckleScript 6
      - name: install-build
        run: |
          esy install 
          esy b
      - name: test-native
        run: |
          esy b dune runtest -f
      - name: test-bsb6
        run: |
          cd tests_bucklescript
          node ./run.js bsb6
      # OCaml 4.02 and BuckleScript 5
      - name: install-build @402
        run: |
          esy @402 install
          esy @402 b
      - name: test-bsb5
        run: |
          cd tests_bucklescript
          node ./run.js bsb5
        env:
          CI: true
